# Generated by Django 5.1.1 on 2024-11-14 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_delete_usuario_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contrasena',
        ),
    ]
